
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
	app: myapp
	type: front-end
codspec:
  replicas: 2
  selector:
	matchLabels:
	  app: myapp
	  type: front-end
  template:
	metadata:
	  labels:
		app: myapp
		type: front-end
	spec:
	containers:
	- name: myapp-container
	  image: myapp-image
	  ports:
	  - containerPort: 8080

